[package]
name = "tinyrick_models"
description = "data models for development tasks"
version = "0.0.1"
edition = "2024"
authors = ["Andrew Pennebaker <n4jm4@pm.me>"]
license = "BSD-2-Clause"
repository = "https://github.com/mcandre/tinyrick_models"
documentation = "https://docs.rs/tinyrick_models/"

[lib]
name = "tinyrick_models"
